name: portfolio
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.8.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  url_launcher: ^6.3.0
  animate_do: ^3.3.4
  vector_math: ^2.1.4
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
